name = "position-guard"
main = "src/index.ts"
compatibility_date = "2026-03-30"
compatibility_flags = ["nodejs_compat"]
minify = false
keep_vars = true

[vars]
HEALTH_PATH = "/health"
TELEGRAM_WEBHOOK_PATH = "/telegram/webhook"

[[d1_databases]]
binding = "DB"
database_name = "position-guard"
database_id = "f675cea3-0dc7-46db-a0e7-b20c2c245f5c"
migrations_dir = "migrations"

[triggers]
crons = ["0 * * * *"]
