import { DEFAULT_PAPER_TRADING_SETTINGS } from "./config.js";

export const PAPER_INITIAL_CASH_KRW = DEFAULT_PAPER_TRADING_SETTINGS.initialPaperCashKrw;
export const PAPER_FEE_RATE = DEFAULT_PAPER_TRADING_SETTINGS.feeRate;
export const PAPER_SLIPPAGE_RATE = DEFAULT_PAPER_TRADING_SETTINGS.slippageRate;
export const PAPER_MIN_TRADE_VALUE_KRW = DEFAULT_PAPER_TRADING_SETTINGS.minimumTradeValueKrw;
export const PAPER_ENTRY_ALLOCATION = DEFAULT_PAPER_TRADING_SETTINGS.entryAllocation;
export const PAPER_ADD_ALLOCATION = DEFAULT_PAPER_TRADING_SETTINGS.addAllocation;
export const PAPER_REDUCE_FRACTION = DEFAULT_PAPER_TRADING_SETTINGS.reduceFraction;
